server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  ai:
    zhipuai:
      api-key: 0f5c5b9d1a664c5f9001246bafa42764.yxhSVBJPcpyLqYsm
      base-url: "https://open.bigmodel.cn/api/paas"
      chat:
        options:
          model: glm-4.5-airx
  http:
    client:
      read-timeout: 1000000


