# 服务器配置
server:
  port: 8888  # 应用服务监听端口，默认8080

spring:
  application:
    name: sangeng-redis-rag
  data:
    # redissearch的配置
    redis:
      host: 127.0.0.1
      port: 6379
      password: app_password
  # Spring AI 配置
  ai:
    # 智谱AI大模型配置
    zhipuai:
      api-key: ${ZHIPU_KEY}
      chat:
        options:
          model: glm-4.6
      embedding:
        options:
          model: embedding-3
          dimensions: 1024    # 如果修改此参数，需要进入redis-cli删除向量index
#    mcp:
#      client:
#        sse:
#          connections:
#            time-server:
#              url: http://127.0.0.1:8080 # mcp服务url
#            fetcher-mcp:
#              url: http://127.0.0.1:3000
    # 向量存储配置
    vectorstore:
      redis:
        initialize-schema: true
#        prefix: "rag:coffee:"
#        index: "rag:coffee:index"
#      pgvector:
#        enabled: true
#        initialize-schema: true